
// REGISTER
POST http://localhost:3000/register
Content-Type: application/json

{
    "username":"talha",
    "email":"talha@gmail.com",
    "password":"123456",
    "roleName":"patient"
}

### LOGIN

POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"ali@gmail.com",
    "password":"123456"
}

### BOOKING APPOINTMENT
POST http://localhost:3000/patients/66bb306e996d7573e0182dce/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmIzMDZlOTk2ZDc1NzNlMDE4MmRjZSIsImlhdCI6MTcyMzU0MzY2MiwiZXhwIjoxNzIzNTQ3MjYyfQ.RijQit8IuzA0BfDIgFILVQl9-7eL39gZUc4yZ1fSwGE

{
    "doctorId":"66bb2fda996d7573e0182db7",
    "notes": "Discuss ongoing stomachache"
}

### READ APPOINTMENT BY PATIENTS
GET http://localhost:3000/patients/66bb2b13be1b67acb55ffc77/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmIzMDAxOTk2ZDc1NzNlMDE4MmRiYiIsImlhdCI6MTcyMzU4NTYwNywiZXhwIjoxNzIzNTg5MjA3fQ.4IWbHCkJcp8wQZfpmTKdLhSUl1Ul_JxrqYpNRhynz_E

### READ APPOINTMENT BY DOCTORS
GET http://localhost:3000/doctors/66b72a91c041f603a80e2682/appointments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YjcyYTkxYzA0MWY2MDNhODBlMjY4MiIsImlhdCI6MTcyMzI4MjQ4MCwiZXhwIjoxNzIzMjg2MDgwfQ.QnHS71wgKU7fnb8Bho5XxtCOMjrtDPMUqsfP3jOtvsI

### READ ALL USERS
GET http://localhost:3000/admin/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Yjc4YjRhOWRhMDBhY2MwNWFkNTM1MiIsImlhdCI6MTcyMzUzNzQ4MSwiZXhwIjoxNzIzNTQxMDgxfQ.80yw1RT-B51kLmwEXwZZeGzfQgO2XqDHjBAo508TV6c

### READ PATIENTS ASSIGNED TO DOCTOR
GET http://localhost:3000/doctors/66bb2fda996d7573e0182db7/patients
Content-Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2YmIyZmRhOTk2ZDc1NzNlMDE4MmRiNyIsImlhdCI6MTcyMzU4NTU2NSwiZXhwIjoxNzIzNTg5MTY1fQ.d0znAVn2JCPM34diBqiLZfsdWpJOx4RS30-Posr1BO4
